language: node_js
sudo: false
node_js:
    - 10
    - 11
install:
    - npm install
    - cp config_example.json config.json
    - cp public_key_fake.json public_key.json
script:
    - npm test -- --coverage
    - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
